name: Update Animeko Sources

on:
  schedule:
    # 每天北京时间 8:00
    - cron: "0 0 * * *"

  workflow_dispatch:


jobs:

  update:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"


    - name: Install dependency
      run: |
        pip install requests


    - name: Merge sources
      run: |
        python auto.py


    - name: Commit update
      run: |

        git config user.name "github-actions"

        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"


        git add auto.json


        git diff --cached --quiet || git commit -m "Auto update Animeko sources"


        git push
